# Site settings
title: Tableau Connector SDK (BETA)
email: github@tableau.com
description: Build connectors to connect to ODBC and JDBC data sources in Tableau.
repository: "tableau/connector-plugin-sdk"
baseurl: "/connector-plugin-sdk"
permalinks: pretty
defaults:
  - scope:
      path: "" # Apply to all files
    values:
      layout: "default"

# Build settings
markdown: kramdown
highlighter: rouge
